import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopHeader from "./components/topHeader";
// import Header from './components/header';
import Footer from "./components/footer";
import { ThemeProvider } from "./components/darkmode/themeProvider";
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<body
						className={`${geistSans.variable} ${geistMono.variable} antialiased`}
					>
						<SignedOut>
							<SignInButton />
							<SignUpButton />
						</SignedOut>
						<SignedIn>
							<UserButton />
						</SignedIn>
						<TopHeader />

						{children}
						<Footer className="mt-36" />
					</body>
				</ThemeProvider>
			</html>
		</ClerkProvider>
	);
}
